### ISSUE TITLE
improve speed by opening mxnet_cudnn_autotune option

### ISSUE THREAD

**Issue by austingg** [pangyupo/mxnet_mtcnn_face_detection#1]
not an issue.

first great jobs. 
you can open mxnet_cudnn_autotune option by `export MXNET_CUDNN_AUTOTUNE_DEFAULT=1` when using gpu and benchmark at the second detection pass. 
on gtx 1080, I get 90ms with your  result image.

**Comment by pangyupo** [comment]
thanks ~ :)

**Comment by yxchng** [comment]
@austingg @pangyupo Is it normal for the code to keep printing "[17:19:52] src/operator/././cudnn_algoreg-inl.h:112: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)"?
