### ISSUE TITLE
Extra region after alignment 

### ISSUE THREAD

**Issue by hajbabaeim** [pangyupo/mxnet_mtcnn_face_detection#14]
Hi.

After using extract_image_chips function, in output img I got some extra region which included none face part.
how can I remove this section from output of extract_image_chips function?

best.

**Comment by hajbabaeim** [comment]
for more explanation:
I expect this one:
![org](https://cloud.githubusercontent.com/assets/25500417/25163853/7aed5f5c-24e2-11e7-89ce-274719e6bd63.png)
but output is:
![chip_0](https://cloud.githubusercontent.com/assets/25500417/25163864/8c425f82-24e2-11e7-97cb-e27c6631c1ad.png)
there is some extra region in right and down of output image (the image shifted to left and upside!).

**Comment by bengouyy** [comment]
you can skip this function if you want a tight bbox, simple use the networks output to crop the image. (as the plot shows)
extract_image_chips adds affine transform which is useful with large pose.

**Comment by hajbabaeim** [comment]
Thanks for your reply @pangyupo . is there any way for me to have a tight bbox like network's output with affine transformation together?
