### ISSUE TITLE
Import error, library missing?

### ISSUE THREAD

**Issue by oxydron** [pangyupo/mxnet_mtcnn_face_detection#15]
Stacktrace:

```Python
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import mxnet as mx
ImportError: No module named 'mxnet'
```

Any tips?

Edit: https://github.com/dmlc/mxnet

**Comment by 123chengbo** [comment]
your mxnet OK？
mxnet-python should be installed first,
cd mxnet/python
python setup.py 

then you can import mxnet

**Comment by oxydron** [comment]
I think you should add this information on the main README.md for this repo.
Best regards.
