### ISSUE TITLE
test2.jpg的运行时间在0.1s左右，请问正常吗

### ISSUE THREAD

**Issue by brantbzhang** [pangyupo/mxnet_mtcnn_face_detection#3]
test2.jpg的运行时间在0.1s左右，请问正常吗。

**Comment by pangyupo** [comment]
虽然不太知道你的配置，我想应该是正常的吧。。。 速度要快的话，几个最直接的方式是把最小人脸弄大，换cpp代码，换gpu换电脑 。。。第一个issue也提到打开cudnn tune的开关也要好一点，不过我电脑一般不明显
