### ISSUE TITLE
I got a RuntimeError.

### ISSUE THREAD

**Issue by LAWSSSS** [pangyupo/mxnet_mtcnn_face_detection#37]
Since I'm using Python 3.5, I made the following changes to the mtcnn_detector.py:
```
try:
    from itertools import izip
except ImportError:
    izip = zip
```
But then when I run the main.py, it says that:

> RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
I don't know what happened.

**Comment by ziqihuang233** [comment]
@LAWSSSS  I have the same problem. Did you solve it？ Pls help.

**Comment by nerddd** [comment]
Same problem, how to solve?

**Comment by LAWSSSS** [comment]
I haven't solved this problem yet. So sorry.
