### ISSUE TITLE
How to change the parameters to prove the detect performance?

### ISSUE THREAD

**Issue by ParadoxZW** [pangyupo/mxnet_mtcnn_face_detection#38]
I set num_worker = 1 , accurate_landmark = False and test on lfw (using your pre-trained model), then there are four photos the model didn't detect out the faces. There are:

- Arsinee_Khanjian_0001.jpg
- John_Wayne_0001.jpg
- Marilyn_Monroe_0002.jpg
- Muhammad_Saeed_al-Sahhaf_0003.jpg

so my question is if there is a way to prove the detect performance a little bit to avoid these four failures? or a practical way to fix（or make up） this problem when it happens during the task of detecting and aligning?

**Comment by AyushP123** [comment]
@ParadoxZW were you able to find out the solution to get detection on all LFW images??
