### ISSUE TITLE
How did you handle matlab caffe model

### ISSUE THREAD

**Issue by cdicle** [pangyupo/mxnet_mtcnn_face_detection#6]
Hi @pangyupo,

Thanks for sharing your implementation. I was wondering how you dealt with the matlab trained caffe weights. Because matlab is column-major and the images are in rgb order. That is how the original network was trained. I implemented a python/caffe version myself but I needed to do necessary transformations to get the correct output. 

Looking forward to hearing from you,
Best,
Cha

**Comment by bengouyy** [comment]
yes, it's a little bit tricky here, how to save the time of transforming image into the required form( transpose and swap channel)... well don't, instead we can change the weight matrix. 
such as:
1 w[:, [0, 2], :, :] = w[:, [0, 2], :, :] , then you don't have to swap the channel anymore, but that only exists in the first conv layer.

2 w[0, 0, :, :] = w[0, 0, :, :].T ,  then you don't need to transpose the image anymore , put this into the loop.

if you look at the final output of the conv layer,  you will find that you have to  adjust the fc layer's weight too.. first reshape it to match the conv's output( something like (number, channel, h, w), then transpose that like 2, then reshape it back )

it's a tedious process, and the code is like 💩 , so I didn't add it into the repo.  hope you get the idea..

**Comment by cdicle** [comment]
Yes, I got it. It was not very clear to me why this was not handled in the matcaffe interface to ensure portability between interfaces. I guess they are portable in the caffe implementation but original authors code had the transformations that made it not portable.

Thanks for the explanation.
