### ISSUE TITLE
It is amazing

### ISSUE THREAD

**Issue by perp** [pangyupo/mxnet_mtcnn_face_detection#7]
![webwxgetmsgimg](https://cloud.githubusercontent.com/assets/2972254/21384119/f9ad010e-c7a3-11e6-83b7-aa0de4f6b9c6.jpg)
original image is below
![pigface](https://cloud.githubusercontent.com/assets/2972254/21384154/3021643c-c7a4-11e6-9b9a-c972eb1a5c3f.jpg)

**Comment by bengouyy** [comment]
😂
