### ISSUE TITLE
how to convert caffemodel to mxnet

### ISSUE THREAD

**Issue by Cv9527** [pangyupo/mxnet_mtcnn_face_detection#9]
as title

**Comment by bengouyy** [comment]
there is a script in Mxnet. [converter](https://github.com/dmlc/mxnet/tree/master/tools/caffe_converter)

and other issues for mtcnn [issue](https://github.com/pangyupo/mxnet_mtcnn_face_detection/issues/6)

**Comment by bengouyy** [comment]
@Cv9527

**Comment by janyoti** [comment]
MXNet now uses nnvm for symbolic API and displays warnings about using an old version of the model files. I tried to use the newest version of the converter, but it failed. Did you manage to convert the models yourself by any chance?
